version: 2
updates:
  - package-ecosystem: "__ECOSYSTEM__"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
